### ISSUE TITLE
Why do we need to transpose in phase_shift

### ISSUE THREAD

**Issue by yifita** [Tetrachrome/subpixel#15]
I'm trying to understand the phase_shift code. But the following step doesn't make much sense to me.
`X = tf.transpose(X, (0, 1, 2, 4, 3))`
https://github.com/Tetrachrome/subpixel/blob/master/subpixel.py#L10

Why do we need this transpose here?

**Comment by EderSantana** [comment]
just to make the order of channels was the one I was expecting.
maybe you can get a better intuition of how this works here: https://github.com/Tetrachrome/subpixel/blob/master/ponynet.ipynb

also, some people argued that you can get similar results of this phase shift with tensorflow builtins tf.depth_to_space. check it out

**Comment by yifita** [comment]
does the order really matter?
it seems to me, since the convolution filters are independent, they don't account for any information how these channels should be "stitched" together spatially. 
So...this ordering wouldn't really matter?

thanks for the quick reply!

**Comment by EderSantana** [comment]
oh yeah. that color switch was supposed to be a temporary hack. I released the code how it was and didn't review it.
for now depth_to_space seems to work to me for most applications. btw, if you have time to proof that depth_to_space get the same results (perhaps remove that extra transpose) we could move it up here to this repo as a more efficient implementation.

**Comment by yifita** [comment]
ok ^^ thanks!
I'll probably use depth_to_space as well, given it's just one call. Thanks!
